# Change these first
owner: server-home-KaKi87 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 'Netdata'
    url: https://netdata.home.kaki87.net
    expectedStatusCodes:
      - 200
  - name: 'Private service #1 - Discord bot'
    url: $PRIVATE_SERVICE_1_URL
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"username":"bot","discriminator":"0000","avatar":null,"status":"online"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.home.kaki87.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Home @ KaKi87 status
  introTitle: "**Home @ KaKi87** server status"
  introMessage: This page shows the status of the services hosted on the Home @ KaKi87 server.
  navbar:
    - title: Status
      href: /
    - title: About
      href: https://home.kaki87.net
  theme: night

assignees:
  - KaKi87

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
